name: gankcamp_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  dio: ^1.0.13
  pull_to_refresh: ^1.1.6
  flutter_spinkit: ^3.1.0
  webview_flutter: ^0.2.0
  url_launcher: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.1

flutter:
  uses-material-design: true